apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: blockchain-nodes
  name: {{ include "eosnode.nodeosfullname" . }}
  labels:
    app: {{ include "eosnode.name" . }}
    chart: {{ include "eosnode.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nodeos
      release: {{ .Release.Name }}
  serviceName: {{ include "eosnode.headlessname" . }}
  template:
    metadata:
      labels:
        app: nodeos
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bash
            - -ec
            - nodeos --snapshot=/data/snapshot.bin {{ include "eosnode.nodeargs" . }} {{ include "eosnode.morenodeargs" . }} {{- if .Values.replay }} --hard-replay {{- end }}
          ports:
            - containerPort: 5557
              protocol: TCP
              name: q2
            - containerPort: 8888
              protocol: TCP
              name: api
            - containerPort: 9876
              protocol: TCP
              name: p2p
            - containerPort: {{ .Values.service.qport }}
              protocol: TCP
              name: queue
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: eos-data
              mountPath: /data
      volumes:
        - name: eos-data
          persistentVolumeClaim:
            claimName: eos-data-claim
  # volumeClaimTemplates:
  #   - metadata:
  #       name: data
  #       labels:
  #         app: {{ include "eosnode.name" . }}
  #         chart: {{ include "eosnode.chart" . }}
  #         release: {{ .Release.Name }}
  #         heritage: {{ .Release.Service }}
  #     spec:
  #       accessModes: [ "ReadWriteOnce" ]
  #       resources:
  #         requests:
  #           storage: {{ .Values.persistence.size | quote }}
  #     {{- if .Values.persistence.storageClass }}
  #       {{- if (eq "-" .Values.persistence.storageClass) }}
  #       storageClassName: ""
  #       {{- else }}
  #       storageClassName: "{{ .Values.persistence.storageClass }}"
  #       {{- end }}        
  #     {{- end }}
